#!/usr/bin/env node
/**
 * Extracts municipios from a Postgres pg_dump (COPY public.municipios ... FROM stdin;)
 * from the "ponto-eletronico" system and generates SQL compatible with VotaLegis.
 *
 * Usage:
 *   node scripts/import_municipios_from_ponto_dump.mjs /path/to/backup_public.sql > municipios.sql
 *
 * Then:
 *   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f municipios.sql
 */

import fs from 'node:fs'

const dumpPath = process.argv[2]
if (!dumpPath) {
  console.error('Usage: node scripts/import_municipios_from_ponto_dump.mjs /path/to/backup_public.sql')
  process.exit(2)
}

const dump = fs.readFileSync(dumpPath, 'utf8')

const copyHeaderRe =
  /^COPY public\.municipios \(([^)]+)\) FROM stdin;$/m

const headerMatch = dump.match(copyHeaderRe)
if (!headerMatch) {
  console.error('Could not find COPY public.municipios (...) FROM stdin; in dump.')
  process.exit(1)
}

const columns = headerMatch[1].split(',').map((s) => s.trim())
const headerLineIdx = dump.indexOf(headerMatch[0])
const dataStartIdx = dump.indexOf('\n', headerLineIdx) + 1
const dataEndIdx = dump.indexOf('\n\\.\n', dataStartIdx)
if (dataEndIdx === -1) {
  console.error('Could not find end of COPY data (\\.) for public.municipios.')
  process.exit(1)
}

const copyData = dump.slice(dataStartIdx, dataEndIdx)
const rows = copyData
  .split('\n')
  .filter((l) => l.length > 0)
  .map((line) => line.split('\t'))

function idx(name) {
  const i = columns.indexOf(name)
  if (i === -1) throw new Error(`Missing column in dump: ${name}`)
  return i
}

function nullify(v) {
  return v === '\\N' ? null : v
}

function sqlString(v) {
  if (v === null || v === undefined) return 'NULL'
  return `'${String(v).replaceAll("'", "''")}'`
}

function sqlBool(v) {
  if (v === null || v === undefined) return 'NULL'
  if (v === 't' || v === 'true' || v === true) return 'TRUE'
  if (v === 'f' || v === 'false' || v === false) return 'FALSE'
  // fall back: treat non-empty as true
  return 'TRUE'
}

const out = []
out.push('-- Generated by scripts/import_municipios_from_ponto_dump.mjs')
out.push('BEGIN;')
out.push('')
out.push('-- Insert municipios (master table in public schema).')
out.push('-- Note: we do NOT set banco_criado=true; schemas are created by the app when you create a camara.')
out.push('')

for (const r of rows) {
  const id = nullify(r[idx('id')])
  const codigoIbge = nullify(r[idx('codigo_ibge')])
  const nome = nullify(r[idx('nome')])
  const uf = nullify(r[idx('uf')])
  const slug = nullify(r[idx('slug')])
  const logoUrl = nullify(r[idx('logo_url')])
  const corPrimaria = nullify(r[idx('cor_primaria')])
  const corSecundaria = nullify(r[idx('cor_secundaria')])
  const ativo = nullify(r[idx('ativo')])
  const cnpj = nullify(r[idx('cnpj')])

  // VotaLegis municipios schema (see database/migrations/*create_users_table.ts):
  // id, nome, slug, uf, codigo_ibge, ativo, status, banco_criado, cnpj, logo_url, cor_primaria, cor_secundaria, total_vereadores, created_at
  // We set status=true for imported records and banco_criado=false.
  out.push(
    [
      'INSERT INTO public.municipios (',
      'id, nome, slug, uf, codigo_ibge, ativo, status, banco_criado, cnpj, logo_url, cor_primaria, cor_secundaria, total_vereadores, created_at',
      ') VALUES (',
      [
        id ?? 'NULL',
        sqlString(nome),
        sqlString(slug),
        sqlString(uf),
        sqlString(codigoIbge),
        sqlBool(ativo),
        'TRUE',
        'FALSE',
        sqlString(cnpj),
        sqlString(logoUrl),
        sqlString(corPrimaria),
        sqlString(corSecundaria),
        '9',
        'NOW()',
      ].join(', '),
      ') ON CONFLICT (id) DO UPDATE SET',
      [
        'nome = EXCLUDED.nome',
        'slug = EXCLUDED.slug',
        'uf = EXCLUDED.uf',
        'codigo_ibge = EXCLUDED.codigo_ibge',
        'ativo = EXCLUDED.ativo',
        'status = EXCLUDED.status',
        'cnpj = EXCLUDED.cnpj',
        'logo_url = EXCLUDED.logo_url',
        'cor_primaria = EXCLUDED.cor_primaria',
        'cor_secundaria = EXCLUDED.cor_secundaria',
        'updated_at = NOW()',
      ].join(', '),
      ';',
    ].join(' ')
  )
}

out.push('')
out.push('-- Fix sequence to max(id)')
out.push(
  "SELECT setval(pg_get_serial_sequence('public.municipios','id'), (SELECT COALESCE(MAX(id), 1) FROM public.municipios));"
)
out.push('')
out.push('COMMIT;')

process.stdout.write(out.join('\n') + '\n')

